### ISSUE TITLE
Issue API get-all-post

### ISSUE THREAD

**Issue by kioku-54** [hikijs/Blog_Backend#24]
Hi @sieusaya149,

Currently, When I call API Get All Post, it will return wrong result.

- URL: /v1/api/post/allPost
- Reponse:

`
{
    "code": 10001,
    "message": "get all posts (friend posts also) success!",
    "metaData": {
        "numberPosts": 1,
        "listPost": null
    }
}
`

You can see, the numberPosts is 1 but listPost is null.
Please take care, thanks!

**Comment by hikijs** [comment]
I have reproduced success this case

create new users testUser1 and testUser2, then making testUser1 and testUser2 to be friend, then testUser1 publishs post with the postPermit = follower. When testUser2 calls /v1/api/post/allPost they will face the issue

**Comment by hikijs** [comment]
thanks @Kioku-Shippuden  for your ticket that will improve our project too much.
Now the issue was fixed by @sieusaya149. Please pull the latest code and test it
